#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 152
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 2
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_PERCENT_LBRACK = 1,
  aux_sym_intent_def_token1 = 2,
  anon_sym_RBRACK = 3,
  anon_sym_AT_LBRACK = 4,
  aux_sym_slot_def_token1 = 5,
  anon_sym_TILDE_LBRACK = 6,
  anon_sym_import = 7,
  aux_sym_import_token1 = 8,
  aux_sym_comment_token1 = 9,
  anon_sym_QMARK = 10,
  aux_sym_word_token1 = 11,
  anon_sym_POUND = 12,
  anon_sym_STAR_LBRACK = 13,
  anon_sym_PERCENT = 14,
  sym_number = 15,
  anon_sym_LPAREN = 16,
  anon_sym_COMMA = 17,
  anon_sym_RPAREN = 18,
  anon_sym_COLON = 19,
  anon_sym_DQUOTE = 20,
  aux_sym_string_token1 = 21,
  anon_sym_SQUOTE = 22,
  aux_sym_string_token2 = 23,
  sym_escape = 24,
  sym__eol = 25,
  sym__indent = 26,
  sym__space = 27,
  sym_source = 28,
  sym__definition = 29,
  sym_intent_def = 30,
  sym_slot_def = 31,
  sym_alias_def = 32,
  sym_import = 33,
  sym_comment = 34,
  sym_intent_body = 35,
  sym_slot_body = 36,
  sym_alias_body = 37,
  sym_slot_ref = 38,
  sym_alias_ref = 39,
  sym_word = 40,
  sym_variation = 41,
  sym_probability = 42,
  sym_arguments = 43,
  sym_argument = 44,
  sym_string = 45,
  aux_sym_source_repeat1 = 46,
  aux_sym_intent_body_repeat1 = 47,
  aux_sym_intent_body_repeat2 = 48,
  aux_sym_slot_body_repeat1 = 49,
  aux_sym_slot_body_repeat2 = 50,
  aux_sym_alias_body_repeat1 = 51,
  aux_sym_word_repeat1 = 52,
  aux_sym_arguments_repeat1 = 53,
  aux_sym_string_repeat1 = 54,
  aux_sym_string_repeat2 = 55,
  alias_sym_intent = 56,
  alias_sym_slot = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT_LBRACK] = "%[",
  [aux_sym_intent_def_token1] = "alias",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT_LBRACK] = "@[",
  [aux_sym_slot_def_token1] = "slot_def_token1",
  [anon_sym_TILDE_LBRACK] = "~[",
  [anon_sym_import] = "import",
  [aux_sym_import_token1] = "file",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_QMARK] = "\?",
  [aux_sym_word_token1] = "word_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_STAR_LBRACK] = "*[",
  [anon_sym_PERCENT] = "%",
  [sym_number] = "number",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_escape] = "escape",
  [sym__eol] = "_eol",
  [sym__indent] = "_indent",
  [sym__space] = "_space",
  [sym_source] = "source",
  [sym__definition] = "_definition",
  [sym_intent_def] = "intent_def",
  [sym_slot_def] = "slot_def",
  [sym_alias_def] = "alias_def",
  [sym_import] = "import",
  [sym_comment] = "comment",
  [sym_intent_body] = "intent_body",
  [sym_slot_body] = "slot_body",
  [sym_alias_body] = "alias_body",
  [sym_slot_ref] = "slot_ref",
  [sym_alias_ref] = "alias_ref",
  [sym_word] = "word",
  [sym_variation] = "variation",
  [sym_probability] = "probability",
  [sym_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_string] = "string",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_intent_body_repeat1] = "intent_body_repeat1",
  [aux_sym_intent_body_repeat2] = "intent_body_repeat2",
  [aux_sym_slot_body_repeat1] = "slot_body_repeat1",
  [aux_sym_slot_body_repeat2] = "slot_body_repeat2",
  [aux_sym_alias_body_repeat1] = "alias_body_repeat1",
  [aux_sym_word_repeat1] = "word_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [alias_sym_intent] = "intent",
  [alias_sym_slot] = "slot",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT_LBRACK] = anon_sym_PERCENT_LBRACK,
  [aux_sym_intent_def_token1] = aux_sym_intent_def_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [aux_sym_slot_def_token1] = aux_sym_slot_def_token1,
  [anon_sym_TILDE_LBRACK] = anon_sym_TILDE_LBRACK,
  [anon_sym_import] = anon_sym_import,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_STAR_LBRACK] = anon_sym_STAR_LBRACK,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_number] = sym_number,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_escape] = sym_escape,
  [sym__eol] = sym__eol,
  [sym__indent] = sym__indent,
  [sym__space] = sym__space,
  [sym_source] = sym_source,
  [sym__definition] = sym__definition,
  [sym_intent_def] = sym_intent_def,
  [sym_slot_def] = sym_slot_def,
  [sym_alias_def] = sym_alias_def,
  [sym_import] = sym_import,
  [sym_comment] = sym_comment,
  [sym_intent_body] = sym_intent_body,
  [sym_slot_body] = sym_slot_body,
  [sym_alias_body] = sym_alias_body,
  [sym_slot_ref] = sym_slot_ref,
  [sym_alias_ref] = sym_alias_ref,
  [sym_word] = sym_word,
  [sym_variation] = sym_variation,
  [sym_probability] = sym_probability,
  [sym_arguments] = sym_arguments,
  [sym_argument] = sym_argument,
  [sym_string] = sym_string,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_intent_body_repeat1] = aux_sym_intent_body_repeat1,
  [aux_sym_intent_body_repeat2] = aux_sym_intent_body_repeat2,
  [aux_sym_slot_body_repeat1] = aux_sym_slot_body_repeat1,
  [aux_sym_slot_body_repeat2] = aux_sym_slot_body_repeat2,
  [aux_sym_alias_body_repeat1] = aux_sym_alias_body_repeat1,
  [aux_sym_word_repeat1] = aux_sym_word_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [alias_sym_intent] = alias_sym_intent,
  [alias_sym_slot] = alias_sym_slot,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_intent_def_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_slot_def_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_intent_def] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_def] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_def] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_intent_body] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_body] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_body] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_variation] = {
    .visible = true,
    .named = true,
  },
  [sym_probability] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_intent_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_intent_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_alias_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_intent] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_slot] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_content = 1,
  field_id = 2,
  field_key = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_id] = "id",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
  [5] = {.index = 2, .length = 2},
  [6] = {.index = 4, .length = 2},
  [7] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_content, 1},
  [2] =
    {field_key, 0},
    {field_value, 2},
  [4] =
    {field_key, 0},
    {field_value, 3},
  [6] =
    {field_key, 0},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = alias_sym_intent,
  },
  [3] = {
    [1] = alias_sym_slot,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 41,
  [52] = 42,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 49,
  [57] = 48,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 58,
  [83] = 83,
  [84] = 59,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 107,
  [112] = 112,
  [113] = 108,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 126,
  [149] = 116,
  [150] = 143,
  [151] = 141,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '\t') ADVANCE(56);
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(57);
      if (lookahead == ' ') ADVANCE(56);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '%') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == ',') ADVANCE(52);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '?') ADVANCE(40);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '%') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == ',') ADVANCE(52);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '?') ADVANCE(40);
      if (lookahead == ']') ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 11:
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == '[') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == '[') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == '[') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == ',') ADVANCE(52);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '0') ADVANCE(48);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '?') ADVANCE(40);
      if (lookahead == '@') ADVANCE(14);
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == '~') ADVANCE(15);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PERCENT_LBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_intent_def_token1);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_slot_def_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_TILDE_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_word_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(34);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(36);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(21);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'u') ADVANCE(25);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          ('t' <= lookahead && lookahead <= 'v')) ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == 'u') ADVANCE(25);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          ('t' <= lookahead && lookahead <= 'v')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 29},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 29},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 29},
  [37] = {.lex_state = 29},
  [38] = {.lex_state = 29},
  [39] = {.lex_state = 29},
  [40] = {.lex_state = 29},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 29},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 10},
  [66] = {.lex_state = 11},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 11},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 29},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 10},
  [79] = {.lex_state = 29},
  [80] = {.lex_state = 29},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 29},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 29},
  [86] = {.lex_state = 29},
  [87] = {.lex_state = 29},
  [88] = {.lex_state = 29},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 29},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 29},
  [93] = {.lex_state = 29},
  [94] = {.lex_state = 29},
  [95] = {.lex_state = 29},
  [96] = {.lex_state = 29},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 29},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 29},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 29},
  [104] = {.lex_state = 29},
  [105] = {.lex_state = 29},
  [106] = {.lex_state = 29},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 29},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 29},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 29},
  [113] = {.lex_state = 29},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 29},
  [116] = {.lex_state = 29},
  [117] = {.lex_state = 29},
  [118] = {.lex_state = 29},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 29},
  [121] = {.lex_state = 3},
  [122] = {.lex_state = 29},
  [123] = {.lex_state = 29},
  [124] = {.lex_state = 29},
  [125] = {.lex_state = 29},
  [126] = {.lex_state = 29},
  [127] = {.lex_state = 29},
  [128] = {.lex_state = 28},
  [129] = {.lex_state = 27},
  [130] = {.lex_state = 26},
  [131] = {.lex_state = 29},
  [132] = {.lex_state = 29},
  [133] = {.lex_state = 29},
  [134] = {.lex_state = 29},
  [135] = {.lex_state = 29},
  [136] = {.lex_state = 29},
  [137] = {.lex_state = 26},
  [138] = {.lex_state = 29},
  [139] = {.lex_state = 27},
  [140] = {.lex_state = 29},
  [141] = {.lex_state = 29},
  [142] = {.lex_state = 29},
  [143] = {.lex_state = 27},
  [144] = {.lex_state = 26},
  [145] = {.lex_state = 29},
  [146] = {.lex_state = 29},
  [147] = {.lex_state = 29},
  [148] = {.lex_state = 29},
  [149] = {.lex_state = 29},
  [150] = {.lex_state = 27},
  [151] = {.lex_state = 29},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [aux_sym_word_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(119),
    [sym__definition] = STATE(2),
    [sym_intent_def] = STATE(37),
    [sym_slot_def] = STATE(37),
    [sym_alias_def] = STATE(37),
    [sym_import] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PERCENT_LBRACK] = ACTIONS(5),
    [anon_sym_AT_LBRACK] = ACTIONS(7),
    [anon_sym_TILDE_LBRACK] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(13),
    [sym__eol] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_PERCENT_LBRACK,
    ACTIONS(7), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(9), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__eol,
    STATE(37), 3,
      sym_intent_def,
      sym_slot_def,
      sym_alias_def,
    STATE(3), 4,
      sym__definition,
      sym_import,
      sym_comment,
      aux_sym_source_repeat1,
  [33] = 9,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_PERCENT_LBRACK,
    ACTIONS(26), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(29), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(32), 1,
      anon_sym_import,
    ACTIONS(35), 1,
      aux_sym_comment_token1,
    ACTIONS(38), 1,
      sym__eol,
    STATE(37), 3,
      sym_intent_def,
      sym_slot_def,
      sym_alias_def,
    STATE(3), 4,
      sym__definition,
      sym_import,
      sym_comment,
      aux_sym_source_repeat1,
  [66] = 8,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(47), 1,
      anon_sym_STAR_LBRACK,
    ACTIONS(49), 1,
      sym__space,
    STATE(13), 1,
      sym_probability,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(5), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [94] = 7,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(51), 1,
      sym__eol,
    ACTIONS(53), 1,
      sym__space,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(7), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [119] = 7,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(53), 1,
      sym__space,
    ACTIONS(55), 1,
      sym__eol,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(7), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [144] = 7,
    ACTIONS(57), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(60), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(63), 1,
      aux_sym_word_token1,
    ACTIONS(66), 1,
      sym__eol,
    ACTIONS(68), 1,
      sym__space,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(7), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [169] = 7,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(53), 1,
      sym__space,
    ACTIONS(71), 1,
      sym__eol,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(7), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [194] = 3,
    ACTIONS(75), 1,
      sym__indent,
    STATE(9), 1,
      aux_sym_intent_body_repeat2,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [210] = 3,
    ACTIONS(80), 1,
      sym__indent,
    STATE(10), 1,
      aux_sym_alias_body_repeat1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [226] = 3,
    ACTIONS(85), 1,
      sym__indent,
    STATE(11), 1,
      aux_sym_slot_body_repeat2,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [242] = 3,
    ACTIONS(90), 1,
      sym__indent,
    STATE(11), 1,
      aux_sym_slot_body_repeat2,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [258] = 6,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(92), 1,
      sym__space,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(8), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [280] = 3,
    ACTIONS(96), 1,
      sym__indent,
    STATE(10), 1,
      aux_sym_alias_body_repeat1,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [296] = 7,
    ACTIONS(98), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(100), 1,
      aux_sym_word_token1,
    ACTIONS(102), 1,
      anon_sym_STAR_LBRACK,
    ACTIONS(104), 1,
      sym__space,
    STATE(33), 1,
      sym_probability,
    STATE(51), 1,
      aux_sym_word_repeat1,
    STATE(23), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [320] = 6,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(106), 1,
      sym__space,
    STATE(41), 1,
      aux_sym_word_repeat1,
    STATE(6), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [342] = 3,
    ACTIONS(110), 1,
      sym__indent,
    STATE(9), 1,
      aux_sym_intent_body_repeat2,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [358] = 1,
    ACTIONS(112), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [369] = 6,
    ACTIONS(98), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(100), 1,
      aux_sym_word_token1,
    ACTIONS(114), 1,
      sym__eol,
    ACTIONS(116), 1,
      sym__space,
    STATE(51), 1,
      aux_sym_word_repeat1,
    STATE(22), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [390] = 1,
    ACTIONS(118), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [401] = 1,
    ACTIONS(120), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [412] = 6,
    ACTIONS(122), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(125), 1,
      aux_sym_word_token1,
    ACTIONS(128), 1,
      sym__eol,
    ACTIONS(130), 1,
      sym__space,
    STATE(51), 1,
      aux_sym_word_repeat1,
    STATE(22), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [433] = 6,
    ACTIONS(98), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(100), 1,
      aux_sym_word_token1,
    ACTIONS(116), 1,
      sym__space,
    ACTIONS(133), 1,
      sym__eol,
    STATE(51), 1,
      aux_sym_word_repeat1,
    STATE(22), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [454] = 1,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [465] = 1,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [476] = 1,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [486] = 1,
    ACTIONS(141), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [496] = 1,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [506] = 1,
    ACTIONS(145), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [516] = 1,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [526] = 1,
    ACTIONS(149), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [536] = 1,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [546] = 5,
    ACTIONS(98), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(100), 1,
      aux_sym_word_token1,
    ACTIONS(153), 1,
      sym__space,
    STATE(51), 1,
      aux_sym_word_repeat1,
    STATE(19), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [564] = 1,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [574] = 1,
    ACTIONS(157), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [584] = 1,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [594] = 1,
    ACTIONS(161), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [604] = 1,
    ACTIONS(163), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [614] = 1,
    ACTIONS(165), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [624] = 1,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [634] = 3,
    ACTIONS(171), 1,
      aux_sym_word_token1,
    STATE(42), 1,
      aux_sym_word_repeat1,
    ACTIONS(169), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [647] = 3,
    ACTIONS(175), 1,
      aux_sym_word_token1,
    STATE(42), 1,
      aux_sym_word_repeat1,
    ACTIONS(173), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [660] = 2,
    ACTIONS(180), 1,
      aux_sym_word_token1,
    ACTIONS(178), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [670] = 5,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    ACTIONS(186), 1,
      sym__space,
    STATE(102), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [686] = 5,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    ACTIONS(188), 1,
      sym__space,
    STATE(97), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [702] = 5,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    ACTIONS(190), 1,
      sym__space,
    STATE(55), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [718] = 2,
    ACTIONS(194), 1,
      aux_sym_word_token1,
    ACTIONS(192), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [728] = 2,
    ACTIONS(198), 1,
      aux_sym_word_token1,
    ACTIONS(196), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [738] = 2,
    ACTIONS(202), 1,
      aux_sym_word_token1,
    ACTIONS(200), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [748] = 2,
    ACTIONS(206), 1,
      aux_sym_word_token1,
    ACTIONS(204), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [758] = 3,
    ACTIONS(208), 1,
      aux_sym_word_token1,
    STATE(52), 1,
      aux_sym_word_repeat1,
    ACTIONS(169), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [770] = 3,
    ACTIONS(210), 1,
      aux_sym_word_token1,
    STATE(52), 1,
      aux_sym_word_repeat1,
    ACTIONS(173), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [782] = 4,
    ACTIONS(213), 1,
      anon_sym_SQUOTE,
    ACTIONS(215), 1,
      aux_sym_string_token2,
    ACTIONS(218), 1,
      sym_escape,
    STATE(53), 1,
      aux_sym_string_repeat2,
  [795] = 4,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    ACTIONS(221), 1,
      sym__space,
    STATE(100), 1,
      sym_string,
  [808] = 4,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    ACTIONS(227), 1,
      sym__space,
    STATE(70), 1,
      aux_sym_arguments_repeat1,
  [821] = 2,
    ACTIONS(202), 1,
      aux_sym_word_token1,
    ACTIONS(200), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [830] = 2,
    ACTIONS(198), 1,
      aux_sym_word_token1,
    ACTIONS(196), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [839] = 2,
    ACTIONS(231), 1,
      aux_sym_word_token1,
    ACTIONS(229), 3,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [848] = 2,
    ACTIONS(235), 1,
      aux_sym_word_token1,
    ACTIONS(233), 3,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [857] = 4,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(239), 1,
      sym__eol,
    ACTIONS(241), 1,
      sym__space,
    STATE(127), 1,
      sym_arguments,
  [870] = 4,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    STATE(91), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [883] = 4,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
    ACTIONS(245), 1,
      aux_sym_string_token1,
    ACTIONS(247), 1,
      sym_escape,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [896] = 4,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      anon_sym_QMARK,
    ACTIONS(253), 1,
      anon_sym_POUND,
    STATE(112), 1,
      sym_variation,
  [909] = 1,
    ACTIONS(255), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym__space,
  [916] = 4,
    ACTIONS(257), 1,
      anon_sym_DQUOTE,
    ACTIONS(259), 1,
      aux_sym_string_token1,
    ACTIONS(261), 1,
      sym_escape,
    STATE(78), 1,
      aux_sym_string_repeat1,
  [929] = 4,
    ACTIONS(257), 1,
      anon_sym_SQUOTE,
    ACTIONS(263), 1,
      aux_sym_string_token2,
    ACTIONS(265), 1,
      sym_escape,
    STATE(53), 1,
      aux_sym_string_repeat2,
  [942] = 4,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      sym__space,
    STATE(74), 1,
      aux_sym_arguments_repeat1,
  [955] = 4,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(271), 1,
      sym__eol,
    ACTIONS(273), 1,
      sym__space,
    STATE(135), 1,
      sym_arguments,
  [968] = 4,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
    ACTIONS(275), 1,
      aux_sym_string_token2,
    ACTIONS(277), 1,
      sym_escape,
    STATE(66), 1,
      aux_sym_string_repeat2,
  [981] = 4,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      sym__space,
    STATE(72), 1,
      aux_sym_arguments_repeat1,
  [994] = 4,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    ACTIONS(279), 1,
      sym__space,
    STATE(99), 1,
      sym_string,
  [1007] = 4,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    ACTIONS(286), 1,
      sym__space,
    STATE(72), 1,
      aux_sym_arguments_repeat1,
  [1020] = 4,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(289), 1,
      sym__eol,
    ACTIONS(291), 1,
      sym__space,
    STATE(140), 1,
      sym_arguments,
  [1033] = 4,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 1,
      sym__space,
    STATE(72), 1,
      aux_sym_arguments_repeat1,
  [1046] = 4,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    STATE(102), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [1059] = 1,
    ACTIONS(297), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym__space,
  [1066] = 4,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(299), 1,
      sym__eol,
    ACTIONS(301), 1,
      sym__space,
    STATE(118), 1,
      sym_arguments,
  [1079] = 4,
    ACTIONS(303), 1,
      anon_sym_DQUOTE,
    ACTIONS(305), 1,
      aux_sym_string_token1,
    ACTIONS(308), 1,
      sym_escape,
    STATE(78), 1,
      aux_sym_string_repeat1,
  [1092] = 4,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    STATE(67), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [1105] = 3,
    ACTIONS(110), 1,
      sym__indent,
    STATE(17), 1,
      aux_sym_intent_body_repeat2,
    STATE(38), 1,
      sym_intent_body,
  [1115] = 3,
    ACTIONS(253), 1,
      anon_sym_POUND,
    ACTIONS(311), 1,
      anon_sym_RBRACK,
    STATE(138), 1,
      sym_variation,
  [1125] = 2,
    ACTIONS(231), 1,
      aux_sym_word_token1,
    ACTIONS(229), 2,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1133] = 3,
    ACTIONS(110), 1,
      sym__indent,
    STATE(17), 1,
      aux_sym_intent_body_repeat2,
    STATE(29), 1,
      sym_intent_body,
  [1143] = 2,
    ACTIONS(235), 1,
      aux_sym_word_token1,
    ACTIONS(233), 2,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1151] = 3,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(313), 1,
      sym__eol,
    STATE(142), 1,
      sym_arguments,
  [1161] = 3,
    ACTIONS(90), 1,
      sym__indent,
    STATE(12), 1,
      aux_sym_slot_body_repeat2,
    STATE(30), 1,
      sym_slot_body,
  [1171] = 3,
    ACTIONS(90), 1,
      sym__indent,
    STATE(12), 1,
      aux_sym_slot_body_repeat2,
    STATE(31), 1,
      sym_slot_body,
  [1181] = 3,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(239), 1,
      sym__eol,
    STATE(127), 1,
      sym_arguments,
  [1191] = 1,
    ACTIONS(315), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1197] = 3,
    ACTIONS(90), 1,
      sym__indent,
    STATE(12), 1,
      aux_sym_slot_body_repeat2,
    STATE(36), 1,
      sym_slot_body,
  [1207] = 1,
    ACTIONS(317), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1213] = 3,
    ACTIONS(110), 1,
      sym__indent,
    STATE(17), 1,
      aux_sym_intent_body_repeat2,
    STATE(35), 1,
      sym_intent_body,
  [1223] = 3,
    ACTIONS(96), 1,
      sym__indent,
    STATE(14), 1,
      aux_sym_alias_body_repeat1,
    STATE(26), 1,
      sym_alias_body,
  [1233] = 3,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(319), 1,
      sym__eol,
    STATE(134), 1,
      sym_arguments,
  [1243] = 3,
    ACTIONS(96), 1,
      sym__indent,
    STATE(14), 1,
      aux_sym_alias_body_repeat1,
    STATE(27), 1,
      sym_alias_body,
  [1253] = 3,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    STATE(89), 1,
      sym_string,
  [1263] = 1,
    ACTIONS(284), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1269] = 3,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    STATE(100), 1,
      sym_string,
  [1279] = 1,
    ACTIONS(321), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1285] = 1,
    ACTIONS(323), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1291] = 3,
    ACTIONS(96), 1,
      sym__indent,
    STATE(14), 1,
      aux_sym_alias_body_repeat1,
    STATE(40), 1,
      sym_alias_body,
  [1301] = 1,
    ACTIONS(325), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1307] = 3,
    ACTIONS(90), 1,
      sym__indent,
    STATE(12), 1,
      aux_sym_slot_body_repeat2,
    STATE(34), 1,
      sym_slot_body,
  [1317] = 3,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(327), 1,
      sym__eol,
    STATE(147), 1,
      sym_arguments,
  [1327] = 1,
    ACTIONS(329), 2,
      anon_sym_RBRACK,
      anon_sym_QMARK,
  [1332] = 2,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(333), 1,
      anon_sym_RPAREN,
  [1339] = 2,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
    ACTIONS(337), 1,
      anon_sym_PERCENT,
  [1346] = 2,
    ACTIONS(339), 1,
      anon_sym_RBRACK,
    ACTIONS(341), 1,
      anon_sym_QMARK,
  [1353] = 2,
    ACTIONS(343), 1,
      sym__eol,
    ACTIONS(345), 1,
      sym__space,
  [1360] = 2,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(331), 1,
      anon_sym_COMMA,
  [1367] = 2,
    ACTIONS(347), 1,
      anon_sym_RBRACK,
    ACTIONS(349), 1,
      anon_sym_PERCENT,
  [1374] = 2,
    ACTIONS(351), 1,
      anon_sym_RBRACK,
    ACTIONS(353), 1,
      anon_sym_QMARK,
  [1381] = 2,
    ACTIONS(355), 1,
      anon_sym_RBRACK,
    ACTIONS(357), 1,
      anon_sym_QMARK,
  [1388] = 2,
    ACTIONS(359), 1,
      anon_sym_COLON,
    ACTIONS(361), 1,
      sym__space,
  [1395] = 2,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(331), 1,
      anon_sym_COMMA,
  [1402] = 1,
    ACTIONS(363), 1,
      anon_sym_RBRACK,
  [1406] = 1,
    ACTIONS(365), 1,
      anon_sym_RBRACK,
  [1410] = 1,
    ACTIONS(327), 1,
      sym__eol,
  [1414] = 1,
    ACTIONS(367), 1,
      ts_builtin_sym_end,
  [1418] = 1,
    ACTIONS(369), 1,
      sym__eol,
  [1422] = 1,
    ACTIONS(371), 1,
      sym__space,
  [1426] = 1,
    ACTIONS(373), 1,
      sym__eol,
  [1430] = 1,
    ACTIONS(331), 1,
      anon_sym_COMMA,
  [1434] = 1,
    ACTIONS(351), 1,
      anon_sym_RBRACK,
  [1438] = 1,
    ACTIONS(375), 1,
      sym__eol,
  [1442] = 1,
    ACTIONS(377), 1,
      anon_sym_RBRACK,
  [1446] = 1,
    ACTIONS(319), 1,
      sym__eol,
  [1450] = 1,
    ACTIONS(379), 1,
      aux_sym_import_token1,
  [1454] = 1,
    ACTIONS(381), 1,
      aux_sym_intent_def_token1,
  [1458] = 1,
    ACTIONS(383), 1,
      aux_sym_slot_def_token1,
  [1462] = 1,
    ACTIONS(385), 1,
      sym__eol,
  [1466] = 1,
    ACTIONS(387), 1,
      sym__eol,
  [1470] = 1,
    ACTIONS(389), 1,
      anon_sym_RBRACK,
  [1474] = 1,
    ACTIONS(391), 1,
      sym__eol,
  [1478] = 1,
    ACTIONS(239), 1,
      sym__eol,
  [1482] = 1,
    ACTIONS(393), 1,
      anon_sym_RBRACK,
  [1486] = 1,
    ACTIONS(395), 1,
      aux_sym_slot_def_token1,
  [1490] = 1,
    ACTIONS(397), 1,
      anon_sym_RBRACK,
  [1494] = 1,
    ACTIONS(399), 1,
      aux_sym_intent_def_token1,
  [1498] = 1,
    ACTIONS(313), 1,
      sym__eol,
  [1502] = 1,
    ACTIONS(401), 1,
      sym_number,
  [1506] = 1,
    ACTIONS(403), 1,
      sym__eol,
  [1510] = 1,
    ACTIONS(405), 1,
      aux_sym_intent_def_token1,
  [1514] = 1,
    ACTIONS(407), 1,
      aux_sym_slot_def_token1,
  [1518] = 1,
    ACTIONS(409), 1,
      anon_sym_COLON,
  [1522] = 1,
    ACTIONS(411), 1,
      sym__eol,
  [1526] = 1,
    ACTIONS(413), 1,
      sym__eol,
  [1530] = 1,
    ACTIONS(415), 1,
      anon_sym_RBRACK,
  [1534] = 1,
    ACTIONS(417), 1,
      anon_sym_RBRACK,
  [1538] = 1,
    ACTIONS(419), 1,
      aux_sym_intent_def_token1,
  [1542] = 1,
    ACTIONS(421), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 169,
  [SMALL_STATE(9)] = 194,
  [SMALL_STATE(10)] = 210,
  [SMALL_STATE(11)] = 226,
  [SMALL_STATE(12)] = 242,
  [SMALL_STATE(13)] = 258,
  [SMALL_STATE(14)] = 280,
  [SMALL_STATE(15)] = 296,
  [SMALL_STATE(16)] = 320,
  [SMALL_STATE(17)] = 342,
  [SMALL_STATE(18)] = 358,
  [SMALL_STATE(19)] = 369,
  [SMALL_STATE(20)] = 390,
  [SMALL_STATE(21)] = 401,
  [SMALL_STATE(22)] = 412,
  [SMALL_STATE(23)] = 433,
  [SMALL_STATE(24)] = 454,
  [SMALL_STATE(25)] = 465,
  [SMALL_STATE(26)] = 476,
  [SMALL_STATE(27)] = 486,
  [SMALL_STATE(28)] = 496,
  [SMALL_STATE(29)] = 506,
  [SMALL_STATE(30)] = 516,
  [SMALL_STATE(31)] = 526,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 546,
  [SMALL_STATE(34)] = 564,
  [SMALL_STATE(35)] = 574,
  [SMALL_STATE(36)] = 584,
  [SMALL_STATE(37)] = 594,
  [SMALL_STATE(38)] = 604,
  [SMALL_STATE(39)] = 614,
  [SMALL_STATE(40)] = 624,
  [SMALL_STATE(41)] = 634,
  [SMALL_STATE(42)] = 647,
  [SMALL_STATE(43)] = 660,
  [SMALL_STATE(44)] = 670,
  [SMALL_STATE(45)] = 686,
  [SMALL_STATE(46)] = 702,
  [SMALL_STATE(47)] = 718,
  [SMALL_STATE(48)] = 728,
  [SMALL_STATE(49)] = 738,
  [SMALL_STATE(50)] = 748,
  [SMALL_STATE(51)] = 758,
  [SMALL_STATE(52)] = 770,
  [SMALL_STATE(53)] = 782,
  [SMALL_STATE(54)] = 795,
  [SMALL_STATE(55)] = 808,
  [SMALL_STATE(56)] = 821,
  [SMALL_STATE(57)] = 830,
  [SMALL_STATE(58)] = 839,
  [SMALL_STATE(59)] = 848,
  [SMALL_STATE(60)] = 857,
  [SMALL_STATE(61)] = 870,
  [SMALL_STATE(62)] = 883,
  [SMALL_STATE(63)] = 896,
  [SMALL_STATE(64)] = 909,
  [SMALL_STATE(65)] = 916,
  [SMALL_STATE(66)] = 929,
  [SMALL_STATE(67)] = 942,
  [SMALL_STATE(68)] = 955,
  [SMALL_STATE(69)] = 968,
  [SMALL_STATE(70)] = 981,
  [SMALL_STATE(71)] = 994,
  [SMALL_STATE(72)] = 1007,
  [SMALL_STATE(73)] = 1020,
  [SMALL_STATE(74)] = 1033,
  [SMALL_STATE(75)] = 1046,
  [SMALL_STATE(76)] = 1059,
  [SMALL_STATE(77)] = 1066,
  [SMALL_STATE(78)] = 1079,
  [SMALL_STATE(79)] = 1092,
  [SMALL_STATE(80)] = 1105,
  [SMALL_STATE(81)] = 1115,
  [SMALL_STATE(82)] = 1125,
  [SMALL_STATE(83)] = 1133,
  [SMALL_STATE(84)] = 1143,
  [SMALL_STATE(85)] = 1151,
  [SMALL_STATE(86)] = 1161,
  [SMALL_STATE(87)] = 1171,
  [SMALL_STATE(88)] = 1181,
  [SMALL_STATE(89)] = 1191,
  [SMALL_STATE(90)] = 1197,
  [SMALL_STATE(91)] = 1207,
  [SMALL_STATE(92)] = 1213,
  [SMALL_STATE(93)] = 1223,
  [SMALL_STATE(94)] = 1233,
  [SMALL_STATE(95)] = 1243,
  [SMALL_STATE(96)] = 1253,
  [SMALL_STATE(97)] = 1263,
  [SMALL_STATE(98)] = 1269,
  [SMALL_STATE(99)] = 1279,
  [SMALL_STATE(100)] = 1285,
  [SMALL_STATE(101)] = 1291,
  [SMALL_STATE(102)] = 1301,
  [SMALL_STATE(103)] = 1307,
  [SMALL_STATE(104)] = 1317,
  [SMALL_STATE(105)] = 1327,
  [SMALL_STATE(106)] = 1332,
  [SMALL_STATE(107)] = 1339,
  [SMALL_STATE(108)] = 1346,
  [SMALL_STATE(109)] = 1353,
  [SMALL_STATE(110)] = 1360,
  [SMALL_STATE(111)] = 1367,
  [SMALL_STATE(112)] = 1374,
  [SMALL_STATE(113)] = 1381,
  [SMALL_STATE(114)] = 1388,
  [SMALL_STATE(115)] = 1395,
  [SMALL_STATE(116)] = 1402,
  [SMALL_STATE(117)] = 1406,
  [SMALL_STATE(118)] = 1410,
  [SMALL_STATE(119)] = 1414,
  [SMALL_STATE(120)] = 1418,
  [SMALL_STATE(121)] = 1422,
  [SMALL_STATE(122)] = 1426,
  [SMALL_STATE(123)] = 1430,
  [SMALL_STATE(124)] = 1434,
  [SMALL_STATE(125)] = 1438,
  [SMALL_STATE(126)] = 1442,
  [SMALL_STATE(127)] = 1446,
  [SMALL_STATE(128)] = 1450,
  [SMALL_STATE(129)] = 1454,
  [SMALL_STATE(130)] = 1458,
  [SMALL_STATE(131)] = 1462,
  [SMALL_STATE(132)] = 1466,
  [SMALL_STATE(133)] = 1470,
  [SMALL_STATE(134)] = 1474,
  [SMALL_STATE(135)] = 1478,
  [SMALL_STATE(136)] = 1482,
  [SMALL_STATE(137)] = 1486,
  [SMALL_STATE(138)] = 1490,
  [SMALL_STATE(139)] = 1494,
  [SMALL_STATE(140)] = 1498,
  [SMALL_STATE(141)] = 1502,
  [SMALL_STATE(142)] = 1506,
  [SMALL_STATE(143)] = 1510,
  [SMALL_STATE(144)] = 1514,
  [SMALL_STATE(145)] = 1518,
  [SMALL_STATE(146)] = 1522,
  [SMALL_STATE(147)] = 1526,
  [SMALL_STATE(148)] = 1530,
  [SMALL_STATE(149)] = 1534,
  [SMALL_STATE(150)] = 1538,
  [SMALL_STATE(151)] = 1542,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(139),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(130),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(129),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(121),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(120),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(144),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(143),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(41),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(7),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2), SHIFT_REPEAT(4),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2), SHIFT_REPEAT(16),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2), SHIFT_REPEAT(15),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_body, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_body, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_body, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 4),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(150),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(51),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(22),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 4),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 7),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 5),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 6, .production_id = 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 5, .production_id = 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 6, .production_id = 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 8, .production_id = 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 5, .production_id = 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 7, .production_id = 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 7, .production_id = 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 6),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(42),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 4, .production_id = 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 4, .production_id = 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 3, .production_id = 3),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 3, .production_id = 3),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 3),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 4),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 4),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 5, .production_id = 3),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 5, .production_id = 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(52),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(53),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(53),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 4),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 4),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 3),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(45),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(123),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 4),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [305] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(78),
  [308] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(78),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 5, .production_id = 7),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 5),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 4, .production_id = 6),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variation, 2, .production_id = 1),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [367] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 5),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 6),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chatito(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
